### ISSUE TITLE
Item content type function not applicable

### ISSUE THREAD

**Issue by ayman-kamruddin** [DallasMorningNews/mbox-tools#3]
Upon running the single available command as prompted, the following error appears:
`Traceback (most recent call last):
  File "/***.py", line *, in <module>
    generate_csv_digest(read_dir+read_file, write_dir+write_file)
  File "***/python3.11/site-packages/mbox_tools/__init__.py", line 58, in generate_csv_digest
    fmt_message['body'] = ' --- MESSAGE PAYLOAD PART BOUNDARY --- '.join([
  File "/opt/miniconda3/envs/search/lib/python3.11/site-packages/mbox_tools/__init__.py", line 60, in <listcomp>
    if item.get_content_type() == 'text/plain'
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_content_type'`

**Comment by ayman-kamruddin** [comment]
Above error occurs due to mishandling of string parts in message multiparts.

Additional error is thrown while handling attachments where `Content-Disposition` does not contain appropriate filename.

Submitting pull request.
